### ISSUE TITLE
Enable importing of `.ts` rules 

### ISSUE THREAD

**Issue by amarjandu** [Nyaran/gplint#419]
I was trying to use gplint to validate custom rules, I converted the file from gherkin-lint's `.js` format to `.ts` in hopes that we could have type annotations to help the development process.

 However it appears that only the `.js` files are supported at runtime.

 https://github.com/Nyaran/gplint/blob/804976ae26a207bb3fb66e367e82214ee0bc19f2/src/rules.ts#LL22C1-L22C82 

When executing with:  

`NODE_ENV=test gplint --config .gherkin-lintrc.json5 features --rulesdir features/gherkin-lint-rules`

the following is outputted;

```
/Users/amar/dev/dev/node_modules/gplint/build/rules/allow-all-caps.d.ts:1
import { GherkinData, RuleSubConfig, RuleError } from '../types';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/amar/dev/dev/node_modules/gplint/build/rules.js:45:26
    at Array.forEach (<anonymous>)

Node.js v18.12.1
```

Am I using the module incorrectly? Is there an easier way to import `.ts` rules? I'd rather not commit both files into our repo, the `.ts` rule file is our "source of truth"...

If there are changes that need to be made please let me know, I'm open to contributing.

**Comment by Nyaran** [comment]
Hi:

Currently only JS files are supported, but I may try to add support for using TS. This month I don't have free time to do it, but if you can/want, you can create a PR, which are always welcome :)

**Comment by Nyaran** [comment]
Support added on v1.5.0, please let me know if there is any issue with it
