### ISSUE TITLE
.gplintignore sample

### ISSUE THREAD

**Issue by mpermperpisang** [Nyaran/gplint#457]
hi
awesome repo

i want to ask about ignore file
do you provide some sample of .gplintignore?
i've tried this content of .gplintignore, but it didn't work

```
xray/*.feature
```

thanks so much

**Comment by Nyaran** [comment]
Hi,

Your example should work, ignoring all .feature files inside xray folder. 
 - That directory is on your working directory (same level as your .gplintrc, .gplintignore, etc)?
 - The directory xray has subdirectories that should be ignored too?

Here you have a working example:
```
gplint-minefield
│   .gplintignore
│   .gplintrc
│   package.json
│
└───features
    │   foo.feature
    │
    └───xray
        │   bar.feature
        │
        └───other
                baz.feature
```

features/foo.feature
```gherkin
Feature: Foo
File at root of "features", should not be ignored

  Scenario: Fooize
    When I do foo
    Given wrong step
````

features/xray/bar.feature
```gherkin
Feature: Bar
File inside xray folder, should be ignored

  Scenario: Barize
    When I do bar
    Given wrong step
````

features/xray/other/bar.feature
```gherkin
Feature: Baz
File in a subfolder in xray, should be ignored

  Scenario: Barize
    When I do bar
    Given wrong step
````

.gplintrc:
```json
{
  "keywords-in-logical-order": "error"
}


Now, if I want to ignore files inside xray directory:

.gplintignore:
```
features/xray/*.feature
```

And that should work, but, with subdirectories, a different wildcard is needed:
.gplintignore:
```
features/xray/**/*.feature
```

Let me know if this help you, if this don't help, please, provide a reproducible example

**Comment by mpermperpisang** [comment]
thanks

i try to running with command `npm run gherkin` since i'm using nodejs
```
  "scripts": {
    "gherkin": "cross-env ./node_modules/.bin/gplint -c ./node_modules/gherkin-lint-sdet/.gplintrc ./test/**/features/ --ignore",
  }
```

but it says `error: option '-i, --ignore <...>' argument missing`
however if i extend with `--ignore .gplintignore`, it still read .feature file in xray folder

@Nyaran

**Comment by Nyaran** [comment]
Oh, I see what is the problem now

You missunderstood the docs (I should improve how is redacted)

## Ignoring Feature Files
There are 2 ways you can specify files that the linter should ignore:
1. Add a `.gplintignore` file in your working directory and specify one glob pattern per file line
2. Use the command line option`-i` or `--ignore`,  pass in a comma separated list of glob patterns. If specified, the command line option will override the `.gplintignore` file.


That means there are two ways to do the same thing, ignore files:
**Way 1: Have a `.gplintignore` file:**
Just create the file with the wildcards to ignore files and run (without `--ignore` parameter):
```shell
gplint -c path/to/your/config
```

**Way 2: Provide the wildcards from cli:**
On the cli command, use the `--ignore` parameter as many times you need to ignore files
```shell
gplint -c path/to/your/config --ignore "xray/*.feature" --ignore "working/*.feature"
```
Note that if you use `--ignore`, the file `.gplintignore` will not be used

So, your script should be like this:

```json
  "scripts": {
    "gherkin": "cross-env ./node_modules/.bin/gplint -c ./node_modules/gherkin-lint-sdet/.gplintrc ./test/**/features/",
  }
```

And don't forget to use the relative path to the xray directory from the working directory

**Comment by mpermperpisang** [comment]
yeah it works now
thanks so much and I'll close this issue
